version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: DockerFile
    ports:
      - "8080:8080"
    depends_on:
      - producer
      - consumer
    networks:
      - app_network

  redis:
    image: "redis:alpine"
    networks:
      - app_network

  consumer:
    build:
      context: ./consumer
      dockerfile: DockerFile
    depends_on:
      - redis
    networks:
      - app_network

  producer:
    build:
      context: ./producer
      dockerfile: DockerFile
    depends_on:
      - redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
