FROM golang:alpine AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

ENV GOPROXY=https://proxy.golang.org,direct

RUN go mod tidy
RUN go mod download

COPY . .

RUN go mod download golang.org/x/sys

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM scratch

COPY --from=builder /app/app .

EXPOSE 8080

CMD ["./app"]
